import { BigHead } from '@bigheads/core'

const Character = (props) => {
  let selected_character;
  if(props.character_code === 'character_01') { selected_character = <BigHead accessory="shades" body="chest" circleColor="blue" clothing="dressShirt" clothingColor="red" eyebrows="serious" eyes="leftTwitch" faceMask={false} faceMaskColor="white" facialHair="none2" graphic="vue" hair="short" hairColor="white" hat="none2" hatColor="white" lashes lipColor="pink" mask mouth="sad" skinTone="brown" style={props.style} /> }
  else if (props.character_code === 'character_02') { selected_character = <BigHead accessory="shades" body="breasts" circleColor="blue" clothing="dressShirt" clothingColor="green" eyebrows="angry" eyes="happy" faceMask={false} faceMaskColor="blue" facialHair="none" graphic="vue" hair="pixie" hairColor="white" hat="none3" hatColor="green" lashes lipColor="green" mask mouth="tongue" skinTone="yellow" style={props.style} />}
  else if (props.character_code === 'character_03') { selected_character = <BigHead accessory="shades" body="breasts" circleColor="blue" clothing="tankTop" clothingColor="green" eyebrows="raised" eyes="happy" faceMask={false} faceMaskColor="black" facialHair="none" graphic="gatsby" hair="short" hairColor="white" hat="turban" hatColor="black" lashes={false} lipColor="purple" mask mouth="sad" skinTone="black" style={props.style} /> }
  else if (props.character_code === 'character_04') { selected_character = <BigHead accessory="none" body="breasts" circleColor="blue" clothing="shirt" clothingColor="black" eyebrows="serious" eyes="happy" faceMask={false} faceMaskColor="red" facialHair="none" graphic="redwood" hair="long" hairColor="orange" hat="none" hatColor="black" lashes lipColor="purple" mask mouth="openSmile" skinTone="yellow" style={props.style} /> }
  else if (props.character_code === 'character_05') { selected_character = <BigHead accessory="none" body="chest" circleColor="blue" clothing="dressShirt" clothingColor="black" eyebrows="leftLowered" eyes="normal" faceMask={false} faceMaskColor="red" facialHair="none2" graphic="graphQL" hair="afro" hairColor="orange" hat="turban" hatColor="green" lashes lipColor="green" mask mouth="open" skinTone="yellow" style={props.style} /> }
  else if (props.character_code === 'character_06') { selected_character = <BigHead accessory="shades" body="chest" circleColor="blue" clothing="shirt" clothingColor="green" eyebrows="raised" eyes="happy" faceMask={false} faceMaskColor="black" facialHair="none" graphic="gatsby" hair="none" hairColor="pink" hat="none4" hatColor="red" lashes={false} lipColor="red" mask mouth="tongue" skinTone="light" style={props.style} /> }
  else if (props.character_code === 'character_07') { selected_character = <BigHead accessory="none" body="breasts" circleColor="blue" clothing="dressShirt" clothingColor="white" eyebrows="leftLowered" eyes="happy" faceMask={false} faceMaskColor="blue" facialHair="none" graphic="vue" hair="bob" hairColor="blonde" hat="none4" hatColor="green" lashes lipColor="green" mask mouth="open" skinTone="red" style={props.style} /> }
  else if (props.character_code === 'character_08') { selected_character = <BigHead accessory="tinyGlasses" body="breasts" circleColor="blue" clothing="vneck" clothingColor="white" eyebrows="leftLowered" eyes="dizzy" faceMask={false} faceMaskColor="red" facialHair="none3" graphic="gatsby" hair="long" hairColor="white" hat="beanie" hatColor="green" lashes lipColor="red" mask mouth="serious" skinTone="light" style={props.style} /> }
  else if (props.character_code === 'character_09') { selected_character = <BigHead accessory="tinyGlasses" body="breasts" circleColor="blue" clothing="vneck" clothingColor="black" eyebrows="leftLowered" eyes="content" faceMask={false} faceMaskColor="red" facialHair="stubble" graphic="react" hair="none" hairColor="brown" hat="none4" hatColor="green" lashes lipColor="green" mask mouth="open" skinTone="light" style={props.style} /> }
  else if (props.character_code === 'character_10') { selected_character = <BigHead accessory="tinyGlasses" body="chest" circleColor="blue" clothing="shirt" clothingColor="red" eyebrows="concerned" eyes="content" faceMask={false} faceMaskColor="red" facialHair="none2" graphic="react" hair="none" hairColor="pink" hat="turban" hatColor="green" lashes lipColor="red" mask mouth="open" skinTone="light" style={props.style} /> }
  else if (props.character_code === 'character_11') { selected_character = <BigHead accessory="tinyGlasses" body="breasts" circleColor="blue" clothing="tankTop" clothingColor="black" eyebrows="leftLowered" eyes="content" faceMask={false} faceMaskColor="black" facialHair="stubble" graphic="redwood" hair="afro" hairColor="orange" hat="turban" hatColor="green" lashes lipColor="pink" mask mouth="open" skinTone="yellow" style={props.style} /> }
  else if (props.character_code === 'character_12') { selected_character = <BigHead accessory="shades" body="chest" circleColor="blue" clothing="tankTop" clothingColor="blue" eyebrows="concerned" eyes="squint" faceMask={false} faceMaskColor="black" facialHair="mediumBeard" graphic="gatsby" hair="none" hairColor="black" hat="none2" hatColor="blue" lashes={false} lipColor="turqoise" mask mouth="sad" skinTone="black" style={props.style} /> }
  else if (props.character_code === 'character_13') { selected_character = <BigHead accessory="tinyGlasses" body="chest" circleColor="blue" clothing="shirt" clothingColor="blue" eyebrows="raised" eyes="simple" faceMask={false} faceMaskColor="black" facialHair="mediumBeard" graphic="gatsby" hair="none" hairColor="orange" hat="none2" hatColor="blue" lashes={false} lipColor="green" mask mouth="openSmile" skinTone="yellow" style={props.style} /> }
  else if (props.character_code === 'character_14') { selected_character = <BigHead accessory="shades" body="breasts" circleColor="blue" clothing="vneck" clothingColor="black" eyebrows="raised" eyes="squint" faceMask={false} faceMaskColor="black" facialHair="none2" graphic="vue" hair="buzz" hairColor="black" hat="none5" hatColor="white" lashes={false} lipColor="purple" mask mouth="tongue" skinTone="dark" style={props.style} /> }
  else if (props.character_code === 'character_15') { selected_character = <BigHead accessory="shades" body="chest" circleColor="blue" clothing="shirt" clothingColor="green" eyebrows="concerned" eyes="simple" faceMask={false} faceMaskColor="red" facialHair="mediumBeard" graphic="graphQL" hair="balding" hairColor="black" hat="none4" hatColor="black" lashes lipColor="red" mask mouth="open" skinTone="red" style={props.style} /> }
  else { selected_character = <BigHead accessory="shades" body="chest" circleColor="blue" clothing="dressShirt" clothingColor="red" eyebrows="serious" eyes="leftTwitch" faceMask={false} faceMaskColor="white" facialHair="none2" graphic="vue" hair="short" hairColor="white" hat="none2" hatColor="white" lashes lipColor="pink" mask mouth="sad" skinTone="brown" style={props.style} /> }
  return selected_character;
}

export default Character;